import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "./components/common/topbar";
import Footer from "./components/common/footer";
import Sidebar from "./components/common/sidebar";
import NavigationBar from "./components/common/navigationbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "Dheeraj Gulati",
    template: "%s | Dheeraj Gulati",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopBar />
        <div className="flex">
          <div>
            <Sidebar />
          </div>
          <div className=" w-[100%] text-white">
            <div>
              <NavigationBar />
            </div>
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
